steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/dfcx-linter-app', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dfcx-linter-app']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'dfcx-linter-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/dfcx-linter-app'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated' # The app handles auth internally
      - '--set-env-vars'
      - 'REDIRECT_URI=https://dfcx-linter-app-uc.a.run.app' # Update this after first deploy if URL differs
      # We need to mount the client_secret.json. 
      # For simplicity in this setup, we will assume it's COPY'd in Dockerfile (NOT SECURE for public repos, but ok for private internal)
      # OR better, use Secret Manager. 
      # Given the user context, we'll rely on the COPY in Dockerfile for now as it's the simplest path forward 
      # and they have the file locally.

images:
  - 'gcr.io/$PROJECT_ID/dfcx-linter-app'
